//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteTeste.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteTeste.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Botao_Buscar {
            get {
                return ResourceManager.GetString("Botao_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Botao_Editar {
            get {
                return ResourceManager.GetString("Botao_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Botao_Gravar {
            get {
                return ResourceManager.GetString("Botao_Gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        public static string Botao_Inserir {
            get {
                return ResourceManager.GetString("Botao_Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Campo_Obrigatorio {
            get {
                return ResourceManager.GetString("Campo_Obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado: {0}, contate o administrador !.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe alguma informação inválida no formulário.
        /// </summary>
        public static string Erro_Formulario {
            get {
                return ResourceManager.GetString("Erro_Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Label_Acoes {
            get {
                return ResourceManager.GetString("Label_Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem Vindo.
        /// </summary>
        public static string Label_Bem_Vindo {
            get {
                return ResourceManager.GetString("Label_Bem_Vindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Regiões do Fornecedor.
        /// </summary>
        public static string Label_Cadastro_Regiao_Fornecedor {
            get {
                return ResourceManager.GetString("Label_Cadastro_Regiao_Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Label_Fornecedor {
            get {
                return ResourceManager.GetString("Label_Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região Fornecedor.
        /// </summary>
        public static string Label_Regiao_Fornecedor {
            get {
                return ResourceManager.GetString("Label_Regiao_Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string Label_Situacao {
            get {
                return ResourceManager.GetString("Label_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Regiões.
        /// </summary>
        public static string Label_Tela_Cadastro_Regiao {
            get {
                return ResourceManager.GetString("Label_Tela_Cadastro_Regiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        public static string Label_Tela_Cadastro_Regiao_Form {
            get {
                return ResourceManager.GetString("Label_Tela_Cadastro_Regiao_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Label_Tela_Cadastro_UF {
            get {
                return ResourceManager.GetString("Label_Tela_Cadastro_UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string Link_Button_Ativar {
            get {
                return ResourceManager.GetString("Link_Button_Ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string Link_Button_Desativar {
            get {
                return ResourceManager.GetString("Link_Button_Desativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Registro Encontado !.
        /// </summary>
        public static string Nenhum_registro_encontrado_GridView {
            get {
                return ResourceManager.GetString("Nenhum_registro_encontrado_GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvo com sucesso.
        /// </summary>
        public static string Salvo_Sucesso {
            get {
                return ResourceManager.GetString("Salvo_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Situacao_Ativo {
            get {
                return ResourceManager.GetString("Situacao_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        public static string Situacao_Inativo {
            get {
                return ResourceManager.GetString("Situacao_Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um fornecedor.
        /// </summary>
        public static string Validacao_DropDownList_Fornecedor {
            get {
                return ResourceManager.GetString("Validacao_DropDownList_Fornecedor", resourceCulture);
            }
        }
    }
}
